version: 2.1

orbs:
  maven: circleci/maven@1.0.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          app_src_directory: 'sesion06Junit/'
          test_results_path: 'sesion06Junit/target/surefire-reports'
